import { Result } from '@/src/result';

describe('Result', () => {
  describe('compensate', () => {
    test('takes the result from the second result, when previous result fails', () => {
      const sut = Result.failure('ðŸ’¥');

      expect(sut.compensate(() => Result.success('âœ…'))).toSucceedWith('âœ…');
    });

    test('takes the result from the first result, when it succeeds', () => {
      const sut = Result.success('âœ…');

      expect(sut.compensate(() => Result.failure('ðŸ’¥'))).toSucceedWith('âœ…');
    });

    test('takes the failure from the second result, when both fail', () => {
      const sut = Result.failure('ðŸ’¥');

      expect(sut.compensate(() => Result.failure('ðŸ’¥ðŸ’¥'))).toFailWith('ðŸ’¥ðŸ’¥');
    });

    test('calls projection with first result error', () => {
      const sut = Result.failure('ðŸ’¥');
      const projection = vi.fn(() => Result.success('âœ…'));

      sut.compensate(projection);
      expect(projection).toBeCalledWith('ðŸ’¥');
    });
  });
});
